name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      
      - name: Install rye
        run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
      
      - name: activate rye
        working-directory: ./websploit
        run: |
          source $HOME/.rye/env
          rye sync
          source .venv/bin/activate
          rye run pytest

      - name: Check test result
        if: failure()
        run: exit 1  # テストが失敗した場合はジョブを失敗させます

      # - name: Setup tmate session for debugging
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3